# Generated by Django 2.1.3 on 2018-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181203_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-package.jpg', upload_to='post_image'),
        ),
    ]
