# Generated by Django 2.1.3 on 2018-12-04 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_candidate', to=settings.AUTH_USER_MODEL),
        ),
    ]
