# Generated by Django 2.1.3 on 2018-12-17 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181204_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adress1',
            field=models.CharField(default='Collection Adress', max_length=100, verbose_name='Collection Address'),
        ),
        migrations.AddField(
            model_name='post',
            name='adress2',
            field=models.CharField(default='Shipping Adress', max_length=100, verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='post',
            name='city1',
            field=models.CharField(default='Berlin', max_length=1024, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='post',
            name='city2',
            field=models.CharField(default='Berlin', max_length=1024, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='post',
            name='zip_code1',
            field=models.CharField(default='1234', max_length=12, verbose_name='ZIP / Postal code'),
        ),
        migrations.AddField(
            model_name='post',
            name='zip_code2',
            field=models.CharField(default='5678', max_length=12, verbose_name='ZIP / Postal code'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
