# Generated by Django 2.1.3 on 2018-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181217_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adress1',
            field=models.CharField(max_length=100, verbose_name='Collection Address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='adress2',
            field=models.CharField(max_length=100, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city1',
            field=models.CharField(max_length=1024, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city2',
            field=models.CharField(max_length=1024, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_code1',
            field=models.CharField(max_length=12, verbose_name='ZIP / Postal code'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_code2',
            field=models.CharField(max_length=12, verbose_name='ZIP / Postal code'),
        ),
    ]
